### ISSUE TITLE
not working in ST3 build 3065

### ISSUE THREAD

**Issue by liyaodong** [sergeche/emmet-sublime#517]
I tried remove emmet and reinstall it , and manually down pyv8 , but it not woring ...

My pyv8 installed in Packages/PyV8 

This is the log:

```
reloading plugin Emmet.emmet-plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Emmet'
```

**Comment by jastuccio** [comment]
Not working for me either in '3065'.  It did work in the past.  I don't see any errors in the console.

**Comment by TheDutchCoder** [comment]
No errors but class expansions like `.foo` aren't working anymore. `div.foo` does.

**Comment by jastuccio** [comment]
I [reset Sublime](https://www.sublimetext.com/docs/3/revert.html) and now Emmet is working.  I will try to post again if I figure out which package it was conflicting with.

**Comment by liyaodong** [comment]
I copy the ST2 emmet file to ST3 ， The problem solved .

**Comment by pacweb** [comment]
I had this problem too in PHP files/sections. It started after I upgraded to ST 3. I was able to fix it by manually installing Emmet. BUT (to finally get it to work) before I downloaded and installed Emmet: I removed the Emmet package in ST, AND trashed both the PyV8 folders under Packages and Installed Packages.  You can get to these through ST by clicking Browse Packages in the ST Preferences.
