### ISSUE TITLE
sibling, child, climb-up doesn't work

### ISSUE THREAD

**Issue by Ariyn** [sergeche/emmet-sublime#518]
hi.
i'm using emmet at ST2 on OSX 10.9
but somehow emmet doesn't change somethings
it still happens after i reinstall emmet and restated ST2.

i found that "sibling", "child", "climb-up", "attribues" doesn't work
![2014-11-09 12 44 45](https://cloud.githubusercontent.com/assets/1639149/4964631/cf305ffe-67a9-11e4-99a0-2946c38dfaf1.png)

and i found some error during loading emmet-plugin.py
this is that log.

Reloading plugin /Users/minuk-hwang/Library/Application Support/Sublime Text 2/Packages/Emmet/emmet-plugin.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./emmet-plugin.py", line 799, in <module>
    init()
  File "./emmet-plugin.py", line 104, in init
    pyv8loader.load(pyv8_paths[1], delegate) 
  File "./emmet/pyv8loader.py", line 47, in load
    config = get_loader_config(dest_path)
  File "./emmet/pyv8loader.py", line 123, in get_loader_config
    for k,v in json.load(fd).items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/**init**.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
##

**Comment by Krabapple** [comment]
Sorry for digging it out, but I have the same problem.
I'm using emmet at ST2 on Win7 x64. How to solve this problem?
Thanks.

**Comment by Ariyn** [comment]
I reinstalled. Try remove st2 and re install st2 and emmet plugin.

**Comment by Ariyn** [comment]
I'll close this issue. If you cant fix problem, please make new issue.
