### ISSUE TITLE
Does not work after update.

### ISSUE THREAD

**Issue by scarlight** [sergeche/emmet-sublime#530]
```
Traceback (most recent call last):
  File "emmet-plugin in C:\Users\vagrant\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 101, in init
  File "emmet-plugin in C:\Users\vagrant\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 248, in update_settings
  File "C:\Users\vagrant\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\context.py", line 261, in js
TypeError: TypeError: Object.keys called on non-object ( emmet-app.js @ 4596 : 9 )  -> 		Object.keys(obj).forEach(function(key) {
```
Hi, I just updated emmet and I got this from sublime console. Now it simply does not work. Any idea what is breaking this? Sublime build version 3065.

**Comment by scarlight** [comment]
Just figured, I removed ```"filters": "css"``` from Emmet.sublime-settings (Settings>User) and it worked.
