### ISSUE TITLE
 Can't expand abbreviation in sublime text 3

### ISSUE THREAD

**Issue by yiye** [sergeche/emmet-sublime#532]
sublime version: v3 build 3065

os: osx yosemite 10.10.1

node: v0.10.29

In sublime console, get the error, when i press TAB or Ctrl + E

```bash
Traceback (most recent call last):
  File "emmet-plugin in /Users/puss/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 375, in run_action
  File "emmet-plugin in /Users/puss/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 324, in _action
TypeError: TypeError: Cannot use 'in' operator to search for 'tag_case' in vm ( emmet-app.js @ 14545 : 16 )  -> 						if (!(key in obj)) {
```

**Comment by pacweb** [comment]
Hi,
I had this problem too in PHP files/sections. It started after I upgraded to ST 3 and I am also using Yosemite. I was able to fix it by manually installing Emmet. BUT (to finally get it to work) before I downloaded and installed Emmet: I removed the Emmet package in ST, AND trashed both the PyV8 folders under Packages and Installed Packages.  You can get to these through ST by clicking Browse Packages in the ST Preferences.
