### ISSUE TITLE
Emmet does not work in Sublime Text 3 Build 3083

### ISSUE THREAD

**Issue by zoorz** [sergeche/emmet-sublime#551]
I installed Emmet to Sublime Text 3 stable Build 3083 but it does not work for me...for example, I set syntax as html, I type html:5 and then press `TAB` and nothing happens...also nothing happens if I type something like this (without quotes):
".container>article+nav", how to fix this? I am running on MAC OSX 10.10.12...

After i reinstall the emmet. Follow the emmet instruction, I found the issue is caused by Pyv8 version not matched. when i install emmet by `Package Control`,It will download Pyv8. But the version is not match.
from the [emmetio/pyv8-binaries][1]
>For Sublime Text 2 (Python 2.6):
>For Sublime Text 3 (Python 3.0):

I got my python version:
 
    $ python --version
    Python 2.7.6

So, I reinstall the pyv8 ,The version is  [OSX 10.7+][2]

The emmet works normally!

[1]: https://github.com/emmetio/pyv8-binaries
[2]: https://github.com/emmetio/pyv8-binaries/raw/master/pyv8-osx-p3.zip

**Comment by sergeche** [comment]
You should check ST console for errors first.

PS: your system Python has nothing to do with ST, it uses it’s own runtime

**Comment by zoorz** [comment]
After I install Emmet, and use `tab` for Expand Abbreviation. There are not errors in ST console.
And after I replace the Pyv8 by myself, It's work OK.

**Comment by sergeche** [comment]
It’s not about Tab key, it’s about package loading. There might be a number of reasons why Emmet doesn’t work and these reasons are not related to Emmet package

**Comment by zoorz** [comment]
Thanks for replay, Maybe you're right.But the issue is solved by replace Pyv8.

**Comment by sergeche** [comment]
OK, if you have any errors in future please create new issue with full ST log

**Comment by zoorz** [comment]
:+1:  No problem

**Comment by danceasarxx** [comment]
I'm having the same problem on my opensuse installation. I just install st3 build 3083 and installed emmet through package control. It's not working and the console is not showing any errors. I don't understand why such should happen

**Comment by sgnl** [comment]
my student is having this problem, here are the errors in the console:

```
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin JsFormat.js_formatter
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-jscs.linter
SublimeLinter: jscs linter loaded 
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin Babel.Babel
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/franpham/Library/Application Support/Sublime Text 3/Packages/PyV8/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: No module named '_PyV8'
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: off 
Package Control: Skipping automatic upgrade, last run at 2015-09-30 11:03:11, next run at 2015-09-30 12:03:11 or after
ignored packages updated to: ["Emmet", "Vintage"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin Emmet.emmet-plugin
generating syntax summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "emmet-plugin in /Users/franpham/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 101, in init
  File "emmet-plugin in /Users/franpham/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 248, in update_settings
  File "/Users/franpham/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
  File "/Users/franpham/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
AttributeError: 'module' object has no attribute 'JSContext'
reloading Packages/User/Preferences.sublime-settings
```

**Comment by zoorz** [comment]
Maybe it caused by package control. For me, After I replace the [emmetio/pyv8-binaries](https://github.com/emmetio/pyv8-binaries),it works. I hope it works for you.
