### ISSUE TITLE
Tab only expand last tag

### ISSUE THREAD

**Issue by nicolasrenon** [sergeche/emmet-sublime#557]
Hello!

I installed Sublime Text 3 on a new Mac with Emmet.  
I followed the following steps :

* Install manually the PyV8 binaries from the repo in Packages/PyV8/_PyV8.so + PyV8.py (from the pyv8-osx-p3.zip)
* Install Emmet through Package Control
* Relaunch ST3

When I try to expand something like

```html
div>ul>li
```
I get this :
```
div>ul><li></li>
```

I tried with `Ctrl+E`, `Cmd+Ctrl+E`, etc. nothing happens :'(

When I start ST3 this is what I get in the console :

```
[...]
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/nrenon/Library/Application Support/Sublime Text 3/Packages/PyV8/PyV8.py", line 32, in <module>
    import _PyV8
ImportError: No module named '_PyV8'
plugins loaded
Traceback (most recent call last):
  File "emmet-plugin in /Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 101, in init
  File "emmet-plugin in /Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 248, in update_settings
  File "/Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
  File "/Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
AttributeError: 'module' object has no attribute 'JSContext'
Package Control: Skipping automatic upgrade, last run at 2015-05-21 08:57:32, next run at 2015-05-21 09:57:32 or after
```

When I tried to track the commands with `sublime.log_commands(True)` I get this :

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 336, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "emmet-plugin in /Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 493, in on_query_context
  File "emmet-plugin in /Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package", line 187, in check_context
  File "/Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 200, in js
    self._use_unicode = should_use_unicode()
  File "/Users/nrenon/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/context.py", line 57, in should_use_unicode
    ctx = PyV8.JSContext()
AttributeError: 'module' object has no attribute 'JSContext'
command: insert_best_completion {"default": "	", "exact": false}
```
Any idea? :)

**Comment by sergeche** [comment]
If you installed Emmet from Package Control, try to put PyV8 into `Installed Packages` folder, not `Packages`

**Comment by nicolasrenon** [comment]
Thank you @sergeche !

![You're awesome](http://i.imgur.com/Gg0Pk.jpg)
