### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by Sergeniy** [sergeche/emmet-sublime#575]
Тут вроде русская поддержка.
Перестал работать emmet в sublime. Ошибка ниже.
Начал использовать Gulp, может что потер им!?
Спасибо.

Emmet: No need to update PyV8
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
Emmet: You have the most recent PyV8 binary
Package Control: No updated packages
Traceback (most recent call last):
  File "C:\Users\Sergeniy\AppData\Roaming\Sublime Text 3\Packages\emmet-sublime-master\emmet-plugin.py", line 375, in run_action
    result = action(max_sel_ix - i, sel) or result
  File "C:\Users\Sergeniy\AppData\Roaming\Sublime Text 3\Packages\emmet-sublime-master\emmet-plugin.py", line 324, in _action
    return c.locals.pyRunAction(name)
TypeError: TypeError: Cannot call method 'shift' of undefined ( emmet-app.js @ 15041 : 42 )  -> 					return rules[isBackward ? i - 1 : i].shift(offset);

**Comment by Sergeniy** [comment]
Поправочка:
в css-файле работает, а styl-файле отказывается, даже если я выбираю синтаксис css вместо stylus

**Comment by Sergeniy** [comment]
Все переустановил, обновил, добился только этого
http://joxi.ru/GrqeqK4hby55rz - (файл .styl) - вверху срабатывает, внизу нет. Как так?

Я уже весь инет перерыл. Помогите уже!

**Comment by xiansheng** [comment]
У меня Jade не работает. А Stylus в Bracket
