### ISSUE TITLE
div*3 couldn't been expended

### ISSUE THREAD

**Issue by zzzgit** [sergeche/emmet-sublime#608]
`"disabled_keymap_actions":"emmet_action_enabled.rename_tag"`
i added this in the user config file
and then,`div*3` couldn't been expended after a pressing on `Tab` key
only `div` or `div.activ` could been expended
why why why

**Comment by sergeche** [comment]
Similar issue was reported a number of times. Please respect my time and check previous issues before creating new one

**Comment by zzzgit** [comment]
```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\sublime_plugin.py", line 354, in on_query_context
    val = callback.on_query_context(v, key, operator, operand, match_all)
  File "emmet-plugin in C:\Users\hotmail.com\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 493, in on_query_context
  File "emmet-plugin in C:\Users\hotmail.com\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 187, in check_context
  File "C:\Users\hotmail.com\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\context.py", line 261, in js
    ctx.locals.pyLoadUserData(self._user_data)
TypeError: TypeError: Object.keys called on non-object ( emmet-app.js @ 4597 : 9 )  -> 		Object.keys(obj).forEach(function(key) {
```

**Comment by sergeche** [comment]
It says there’s something wrong with you custom data for extending Emmet

**Comment by zzzgit** [comment]
```javascript
{
	"snippets":{
		"html": {
			"abbreviations": {
				"script": "<script type=\"text/javascript\"></script>"
			}
		},
		//"disabled_keymap_actions":"emmet_action_enabled.rename_tag" // if i uncomment this sentence,div*3 will not work at all
	}
}
```
what is the matter with the last sentence?

**Comment by zzzgit** [comment]
now i see,the place is wrong
it should be:
```
{
    "snippets":{
        "html": {
            "abbreviations": {
                "script": "<script type=\"text/javascript\"></script>"
            }
        }
    },
 //"disabled_keymap_actions":"emmet_action_enabled.rename_tag" 
}
```
