### ISSUE TITLE
Emmet breaks on Sublime Text 3 3126 for linux

### ISSUE THREAD

**Issue by pixelprogrammer** [sergeche/emmet-sublime#639]
I have Sublime Text 3 installed on a Fedora install. Emmet was working but it appears that it has stopped since one of the updates (unfortunately I am not sure which one).

Here is the part of the console that seems to be having an issue after initial load:

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "emmet-plugin in /home/joemoe/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/joemoe/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 20, in <module>
AttributeError: 'module' object has no attribute 'error'
```

Just in case its needed, here is the full dump.

```
DPI scale: 1
startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /
packages path: /home/joemoe/.config/sublime-text-3/Packages
state path: /home/joemoe/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/joemoe/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.163585
startup time: 0.21097
first paint time: 0.223465
first paint time: 0.230454
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
Package Control: Linux SSL: unloading http module so ssl will be available
Package Control: Linux SSL: unloading urllib module so ssl will be available
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin DocBlockr.jsdocs
reloading plugin Emmet.emmet-plugin
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text_3/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "emmet-plugin in /home/joemoe/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/joemoe/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 20, in <module>
AttributeError: 'module' object has no attribute 'error'
reloading plugin Markdown HTML Preview.MarkdownHtmlPreview
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin GoSublime.GoSublime
reloading plugin GoSublime.gs9o
reloading plugin GoSublime.gscommands
reloading plugin GoSublime.gscomplete
reloading plugin GoSublime.gsdoc
reloading plugin GoSublime.gsev
reloading plugin GoSublime.gslint
reloading plugin GoSublime.gspalette
reloading plugin GoSublime.gssynforce
reloading plugin GoSublime.gstest
reloading plugin TodoReview.TodoReview
plugins loaded
GoSublime r16.07.09-1: init mod(gs)
GoSublime r16.07.09-1: init mod(sh)
GoSublime r16.07.09-1 sh: load env vars ['/bin/bash', '-l', '-c', 'echo "..."']: go version: ['/usr/local/go/bin/go', 'version'] -> `go version go1.7 linux/amd64
` -> `go1.7`: 0.084s
GoSublime r16.07.09-1: init mod(mg9)

** 2016-10-15 17:27:49.973566 **:
GoSublime init r16.07.09-1 (0.000s)
|   install margo: no
|   install state: done
| sublime.version: 3126
| sublime.channel: stable
|       about.ann: a16.07.09-1
|   about.version: r16.07.09-1
|         version: r16.07.09-1
|        platform: linux-x64
|            ~bin: ~/.config/sublime-text-3/Packages/User/GoSublime/linux-x64/bin
|       margo.exe: ~bin/gosublime.margo_r16.07.09-1_go1.7.exe (ok)
|          go.exe: /usr/local/go/bin/go (ok)
|      go.version: go1.7
|          GOROOT: /usr/local/go
|          GOPATH: ~/gocode
|           GOBIN: (not set) (should usually be `(not set)`)
|       set.shell: []
|       env.shell: /bin/bash
|       shell.cmd: ['/bin/bash', '-l', '-c', '${CMD}']
--------------------------------

Package Control: Skipping automatic upgrade, last run at 2016-10-15 16:46:47, next run at 2016-10-15 17:46:47 or after
```

Is there any idea why it breaks at this point?

**Comment by dakira** [comment]
I can confirm this. It breaks on all my Linux installs.

**Comment by SubodhDahal** [comment]
Looks to me like the same issue as https://github.com/sergeche/emmet-sublime/issues/636, which has been closed. Have a look at that.

**Comment by pixelprogrammer** [comment]
I just tested this last night and Emmet appears to be working again. Not sure if it was an update to Emmet or another plugin that fixed it but its working at the moment.
