### ISSUE TITLE
Emmet.emmet-plugin fails to load properly due to module error on startup thus no autocompletions working anymore.

### ISSUE THREAD

**Issue by kailashyogeshwar85** [sergeche/emmet-sublime#641]
`reloading plugin Emmet.emmet-plugin
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "emmet-plugin in /home/kailash/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/kailash/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 20, in <module>
AttributeError: 'module' object has no attribute 'error'`

**Comment by jbarreiros** [comment]
There is probably a better way, but I had the same problem and ended up fixing it by clearing out my data directory (except for the Packages/User folder of course), restarting Sublime and, finally, installing Package Control to resinstall all of my plugins. After that, Emmet was working again.
