### ISSUE TITLE
Pressing TAB after more than one element doesn't work in sublime 3

### ISSUE THREAD

**Issue by naveenkakani** [sergeche/emmet-sublime#652]
Emmet is not working when I'm trying to do something like this
`section#cover>#cover-caption`
But, It is working fine with just one element like
`section#cover`

**Comment by mugukamil** [comment]
After update emmet doesnt working in sublime text... :(

**Comment by jgbishop** [comment]
I see the following error in the console:
```
Traceback (most recent call last):
  File "...\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "emmet-plugin in ...\Emmet.sublime-package", line 497, in on_query_completions
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by amaurycatelan** [comment]
Have you tried? - #578

> Try to restart Sublime Text and check ST console for errors

**Comment by jgbishop** [comment]
Restarting doesn't help. Given that emmet updated yesterday, I'm guessing this bug is due to commit #654. Things were working just fine a few days ago.

**Comment by jgbishop** [comment]
Hmm. Well, now things appear to work. Strange. I'm 100% sure I restarted and it continued to fail, but now things appear to work again. 😕

**Comment by tvercruysse** [comment]
Control+Z and tapping again works for me, but this sure is a bug that should be addressed.

Also dont hijack a issue guys, instead open a new one.

**Comment by joemaller** [comment]
Same deal as @jgbishop, Emmet was mostly broken after an update, restarting didn't fix it  (I'm certain I did, including removing and re-installing Emmet). Just restarted Sublime again and now Emmet is working correctly. Wish there was something more constructive I could offer, but I'm glad to have it back.

**Comment by naveenkakani** [comment]
Let's hope this will be fixed soon. This feature makes emmet what it is.

**Comment by HonnKing** [comment]
I had the same issue, had to really do a force restart of sublime. Just closing it an opening again didn't cut it, had to make sure all sublime processes where actually dead.

Did it after reinstalling the plugin, and now it works again.
