### ISSUE TITLE
"No JSON object could be decoded" error every time I launch ST3

### ISSUE THREAD

**Issue by ZaLiTHkA** [sergeche/emmet-sublime#672]
Greetings.. 🖖  I don't work with Python at all, so I apologise if the solution to this problem is simple.. Unfortunately it's not obvious to me.

Everytime I launch ST3 (build 3143, Windows 10 x64) I get the following message in the console ([full console output here](https://gist.github.com/ZaLiTHkA/2d08359ad0195527c16dd502e3e3de0a)):

```
plugins loaded
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emmet-plugin in C:\Users\agreeff\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 104, in init
  File "C:\Users\agreeff\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 47, in load
  File "C:\Users\agreeff\AppData\Roaming\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 123, in get_loader_config
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

I've looked through my user folder for any and all config files that may be used by Emmet Sublime, either just to check their syntax or delete them to force a re-generate. I've tried removing and reinstalling the Emmet plugin.

What file is this failing to parse?? Emmet itself does actually work, but I hate seeing error messages, even if they don't actually "break" anything, but especially if I don't know what they mean.

**Comment by ZaLiTHkA** [comment]
so this error has been bugging me for a while now... finally took the time this morning to look through the files listed in the traceback message: turns out this was caused by the the fact that my `Installed Packages/PyV8/config.json` file was completely blank and therefore "not valid JSON".

after simply inserting an empty object wrapper `{}` into this file, ST3 launches and this plugin loads without any errors.

**Comment by cluis13915** [comment]
Not worked for me ! I have the JSON config file in `sublime-text-3/Packages/PyV8/linux64-p3/` folder.
