### ISSUE TITLE
AttributeError: 'module' object has no attribute 'error'

### ISSUE THREAD

**Issue by igorsol** [sergeche/emmet-sublime#674]
I have this configuration:
- Ubuntu 16.04
- ST3 build 3143
- Package COntrol version 3.3.0
- Emmet v2017.03.23 21:16:14 (installed via package control)

Emmet plugin does not work for me (only last part is expanded on `TAB` press). So I did a small investigation.
On ST3 start there is an error in the console:
```
reloading plugin Emmet.emmet-plugin
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "emmet-plugin in /home/user/.config/sublime-text-3/Installed Packages/Emmet.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/home/user/.config/sublime-text-3/Installed Packages/Emmet.sublime-package/emmet/pyv8loader.py", line 20, in <module>
AttributeError: 'module' object has no attribute 'error'
```
As you can see the problem is in line 20 of pyv8loader.py:
```
import urllib.error as url_err
```
So tried to execute some tests in interactive mode from the ST3 console. My first test was to get python version:
```
>>> import sys; sys.version_info
sys.version_info(major=3, minor=3, micro=6, releaselevel='final', serial=0)
```
Then I tried to execute line 20 manually:
```
>>> import sys; import urllib.error as url_err; sys.version_info
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'error'
```
It does not work. Then I tried with slightly altered line 20 (without `as url_err` clause):
```
>>> import sys; import urllib.error; sys.version_info
sys.version_info(major=3, minor=3, micro=6, releaselevel='final', serial=0)
```
It works. Not sure what does it mean since I'm not big python specialist. I hope this small investigation will help to localize the issue.
P.S: I tried to reinstall Emmet several times but that does not help.

**Comment by sergeche** [comment]
See https://github.com/wbond/package_control/issues/1174

**Comment by igorsol** [comment]
Thanks. As was suggested in the above link removing `Installed Packages/0_package_control_loader.sublime-package` and restarting ST3 cured my system.
