### ISSUE TITLE
Indent troubles with ST4

### ISSUE THREAD

**Issue by kud** [sergeche/emmet-sublime#726]
I can't indent anymore with ST4 due to Emmet.

Logs:

```
Traceback (most recent call last):
  File "/Users/kud/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet-plugin.py", line 376, in run_action
    result = action(max_sel_ix - i, sel) or result
  File "/Users/kud/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet-plugin.py", line 325, in _action
    return c.locals.pyRunAction(name)
TypeError: TypeError: Cannot call method 'shift' of undefined ( emmet-app.js @ 15041 : 42 )  -> 					return rules[isBackward ? i - 1 : i].shift(offset);
```

**Comment by sergeche** [comment]
Please try this plugin: https://github.com/emmetio/sublime-text-plugin

**Comment by kud** [comment]
I'm sorry, I discovered it just after posting my issue, haha, yeah it works now indeed, thank you!
